export const students = [
  {
    id: 1,
    name: "Anvar",
    status: "teacher",
    age: 24,
    address: "Fergana",
    nicname: "@Anvar",
    hobby: "Football",
  },
  {
    id: 2,
    name: "Ulug'bek",
    status: "IT guy",
    age: 22,
    address: "Qo'qon",
    nicname: "@Ulugbek",
    hobby: "Draw",
  },
  {
    id: 3,
    name: "Bobur",
    status: "teacher",
    age: 23,
    address: "Fergana",
    nicname: "@Bobur",
    hobby: "Football",
  },
  {
    id: 4,
    name: "Xusrav",
    status: "programmist",
    age: 20,
    address: "Novoiy",
    nicname: "@Xusrav",
    hobby: "Voleboll",
  },
  {
    id: 5,
    name: "Odilbek",
    status: "teacher",
    age: 26,
    address: "Fergana",
    nicname: "@Odilbek",
    hobby: "Football",
  },
  {
    id: 6,
    name: "Jahongir",
    status: "IT guy",
    age: 22,
    address: "Buxoro",
    nicname: "@Jahongir",
    hobby: "Sing",
  },
  {
    id: 7,
    name: "Sanjar",
    status: "Developer",
    age: 21,
    address: "Fergana",
    nicname: "@Sanjar",
    hobby: "Math",
  },
  {
    id: 8,
    name: "Asror",
    status: "Operator",
    age: 20,
    address: "Marg'ilon",
    nicname: "@Asror",
    hobby: "movies",
  },
  {
    id: 9,
    name: "Ziyovvudin",
    status: "IT guy",
    age: 19,
    address: "Samarqand",
    nicname: "@Ziyovvudin",
    hobby: "Football",
  },
  {
    id: 10,
    name: "Muhriddin",
    status: "Translator",
    age: 23,
    address: "Andijon",
    nicname: "@Muhriddin",
    hobby: "Math",
  },
];
